In [12]:
import pandas as pd
import numpy as np
import sys
import csv

In [15]:
csv.field_size_limit(sys.maxsize)

df = pd.read_csv(
    "/content/email_dataset_classification.csv",
    engine='python',
    on_bad_lines='skip'
)

In [23]:
print(df.shape)
df.head()

(298166, 3)

   Unnamed: 0                                            message  label
0           0  ['Fabulous discounts from CanadianPharmacy. 50...      1
1           1                      http://houston.cowparade.net/      0
2           2  =================================\n\nGuarantee...      1
3           3  Thanks for your help! ----------------------  ...      0
4           4  Start Date: 10/13/01; HourAhead hour: 23; No a...      0

In [46]:
df["message"][2021]

"\nDear Users,\n\nI am new to R, I have just downloaded it to play with. I am a Java  & \nMatlab user, so I assume that it  wouldn't be a hurdle.  Where do I get \nto see the source codes for R  sub-packages  ? I looked at those \nsub-packages in folder  'R-ex'  for the source codes and they are \ncompressed files.  Do I mean to de-compress these files where the source \ncodes reside ?\n\nAny hint would be useful.\n\nCheers,\nSione.\n\n______________________________________________\nR-help@stat.math.ethz.ch mailing list\nhttps://stat.ethz.ch/mailman/listinfo/r-help\nPLEASE do read the posting guide http://www.R-project.org/posting-guide.html\nand provide commented, minimal, self-contained, reproducible code.\n\n"

In [30]:
< > [] \n https link * email id - _

SyntaxError: invalid syntax (3955887718.py, line 1)

In [58]:
import re

def clean_email(text):
    text = text.lower()

    text = re.sub(r'https?\s*:\s*/\s*/\s*\S+', ' URL ', text)
    text = re.sub(r'\S+@\S+', ' EMAIL ', text)
    text = re.sub(r'[<>\[\]\*]', '', text)
    text = text.replace('\n', ' ')
    text = re.sub(r'[-_]', ' ', text)
    text = re.sub(r'\s+', ' ', text).strip()

    return text

In [59]:
df['clean_text'] = df['message'].apply(clean_email)

In [50]:
df.head()

,Unnamed: 0,message,label,clean_text
0,0,['Fabulous discounts from CanadianPharmacy. 50...,1,'fabulous discounts from canadianpharmacy. 50%...
1,1,http://houston.cowparade.net/,0,URL
2,2,=================================\n\nGuarantee...,1,================================= guaranteed t...
3,3,Thanks for your help! ---------------------- ...,0,thanks for your help! tana jones/hou/ect on 09...
4,4,Start Date: 10/13/01; HourAhead hour: 23; No a...,0,start date: 10/13/01; hourahead hour: 23; no a...

In [65]:
for i in range(10):
  print(df["message"][i*1000])
  print("="*50)
  print(df["clean_text"][i*1000])
  print(


  )

['Fabulous discounts from CanadianPharmacy. 50% discounts on all products when you purchase during the summer period. http: / / nationspecial. hk Absolutely downcast prices, caring staff, good and quick shipping, high level of protection, and top quality products are the most common characteristics mentioned by our customers in their recommendation. CanadianPharmacy is proud to be the most popular Canadian drugstore online. Purchase with CanadianPharmacy. Order with CanadianPharmacy and get incredible summer deduction. http: / / nationspecial. hk']
==================================================
'fabulous discounts from canadianpharmacy. 50% discounts on all products when you purchase during the summer period. URL hk absolutely downcast prices, caring staff, good and quick shipping, high level of protection, and top quality products are the most common characteristics mentioned by our customers in their recommendation. canadianpharmacy is proud to be the most popular canadian drugstore online. purchase with canadianpharmacy. order with canadianpharmacy and get incredible summer deduction. URL hk'

Attached is an Omnibus Confirmation for NG Trading LLC. If you have any questions, please feel free to call. Regards, Brad
==================================================
attached is an omnibus confirmation for ng trading llc. if you have any questions, please feel free to call. regards, brad

CalPeak was formed as a project company, and is being funded by UTC. CalPeak was formed less than two months ago, and has no financials. We will provide a pro forma balance sheet should the bidder be selected. Types of typical project support are things like a UT gurantee for one month's fuel supply, etc. Chuck -----  ----- cchinckley.com> > Sent: Monday, April 02, 2001 2:39 PM > Subject: Re: CalPeak Power RFP - Shortlist > > > > > > Ann, > > > > I just spoke with Jay Williams from our credit department and he only > needs > > CalPeak's latest audited financial statements with management notes. Any > > additional information that helps us understand the company and how it is > > set up will be helpful. Sending this information overnight will probobly > > be our best bet. My address is as follows: > > > > 1400 Smith Street, EB3206a > > Houston, TX 77002 > > > > Also, Jay's phone number is 713-345-3923. Let me know if you have any > > questions. > > > > Thanks, > > > > Kim > > > > > > > > > > > > > >
==================================================
calpeak was formed as a project company, and is being funded by utc. calpeak was formed less than two months ago, and has no financials. we will provide a pro forma balance sheet should the bidder be selected. types of typical project support are things like a ut gurantee for one month's fuel supply, etc. chuck cchinckley.com sent: monday, april 02, 2001 2:39 pm subject: re: calpeak power rfp shortlist ann, i just spoke with jay williams from our credit department and he only needs calpeak's latest audited financial statements with management notes. any additional information that helps us understand the company and how it is set up will be helpful. sending this information overnight will probobly be our best bet. my address is as follows: 1400 smith street, eb3206a houston, tx 77002 also, jay's phone number is 713 345 3923. let me know if you have any questions. thanks, kim

['look at that prices vaio ® sz series vgn arescapenumbere gbp escapenumber escapenumber escapenumber escapenumber escapenumber escapenumber sony playstation escapenumber premium gbp escapenumber escapenumber escapenumber escapenumber canon eos escapenumberd digital slr camera gbp escapenumber escapenumber escapenumber escapenumber escapenumber apple ipod digital player hd escapenumber gb aac mpescapenumber gbp escapenumber escapenumber escapenumber escapenumber sony escapelong lcd projection gbp escapenumber escapenumber escapenumber escapenumber sony escapelong hd ready gbp escapenumber escapenumber escapenumber escapenumber escapenumber we give you escapenumber escapenumber discount from bizrate prices escapenumber reasons to buy from us responsible and accessible escapenumber day exchange escapenumber day return no questions ask free delivery ultimate price promise entanglement site of our shop for face for huge variety of hebdomadary plus t ball compared with weekly plus t ball strain for children']
==================================================
'look at that prices vaio ® sz series vgn arescapenumbere gbp escapenumber escapenumber escapenumber escapenumber escapenumber escapenumber sony playstation escapenumber premium gbp escapenumber escapenumber escapenumber escapenumber canon eos escapenumberd digital slr camera gbp escapenumber escapenumber escapenumber escapenumber escapenumber apple ipod digital player hd escapenumber gb aac mpescapenumber gbp escapenumber escapenumber escapenumber escapenumber sony escapelong lcd projection gbp escapenumber escapenumber escapenumber escapenumber sony escapelong hd ready gbp escapenumber escapenumber escapenumber escapenumber escapenumber we give you escapenumber escapenumber discount from bizrate prices escapenumber reasons to buy from us responsible and accessible escapenumber day exchange escapenumber day return no questions ask free delivery ultimate price promise entanglement site of our shop for face for huge variety of hebdomadary plus t ball compared with weekly plus t ball strain for children'




CNN Alerts: My Custom Alert










Alert Name: My Custom Alert
The ultimate secret to unlocking the most powerful feature in you iPhone.

Fri, 8 Aug 2008 11:40:16 +0200

FULL STORY



You have agreed to receive this email from CNN.com as a result of your CNN.com preference settings.
To manage your settings click here.
To alter your alert criteria or frequency or to unsubscribe from receiving custom email alerts, click here.


Cable News Network. One CNN Center, Atlanta, Georgia 30303
© 2008 Cable News Network.
A Time Warner Company
All Rights Reserved.
View our privacy policy and terms.







==================================================
cnn alerts: my custom alert alert name: my custom alert the ultimate secret to unlocking the most powerful feature in you iphone. fri, 8 aug 2008 11:40:16 +0200 full story you have agreed to receive this email from cnn.com as a result of your cnn.com preference settings. to manage your settings click here. to alter your alert criteria or frequency or to unsubscribe from receiving custom email alerts, click here. cable news network. one cnn center, atlanta, georgia 30303 © 2008 cable news network. a time warner company all rights reserved. view our privacy policy and terms.

Alert! You are receiving this message because you have an unresolved invoice in your iPayit in-box that is past due. It is critical that you login to iPayit and take immediate action to resolve this invoice. Remember, you play an important role in ensuring that we pay our vendors on time. Tip!: You must login to the system to forward this invoice to another user. To launch iPayit, click on the link below: http://iPayit.enron.com Note: Your iPayit User ID and Password are your eHRonline/SAP Personnel ID and Password. First time iPayit user? For training materials, click on the link below: http://sap.enron.com/sap_doclib/user/file_list.asp?cabinet_id=265 Need help? North America: ISC Call Center at (713) 345-4727. Europe: European Accounts Payable at +44-20-7783-7520. Asia-Pacific: Sydney Accounts Payable at +61-2-9229-2336
==================================================
alert! you are receiving this message because you have an unresolved invoice in your ipayit in box that is past due. it is critical that you login to ipayit and take immediate action to resolve this invoice. remember, you play an important role in ensuring that we pay our vendors on time. tip!: you must login to the system to forward this invoice to another user. to launch ipayit, click on the link below: URL note: your ipayit user id and password are your ehronline/sap personnel id and password. first time ipayit user? for training materials, click on the link below: URL need help? north america: isc call center at (713) 345 4727. europe: european accounts payable at +44 20 7783 7520. asia pacific: sydney accounts payable at +61 2 9229 2336

['Royal Meds _ your online = pharmacy = B7 Click Here_ - - - Your online pharmacy for _ * * FDA approv = ed * * _ drugs through a online consultation. No more awkward doctor visits, we offer confidential ordering onlin = e. Take advantage of some of best prices uncommitted on the Internet! We offer the widest range of drugs available through online ordering. * * = _Such as: _ * * |! [] (3D " http: / / www. royalmeds. com / images / viag - head. jp =) - - - _ * * = Less than $ 7. 00 per dose * * _ * * Viagra * * Inten = ded for men with erectile dysfunction (ED ), it helps most men to get and = keep an erection when they get sexually excited. No need to go through em = barrassing, stressful situation anymore, you can now gravel Viagra from the = comfort of your home. * * Click Here * * |! [] (3D " http: / / www. royalmeds. com / images / phen - head. jp =) - - - * * Phentermine * * Obesity weight loss dr = ug. It enables people to burn more fat doing nothing, stimulating your ne = rvous system. You will feel the difference! It will give you more energy, = you will become more active! It \' s an appetite suppressant, you \' ll burn f = at easier and eat less. It is a both safe and effective treatment to lose = weight. * * Cli = ck Here * * |! [] (3D " http: / / world wide web. royalmeds. com / images / zyban - head. j =) - - - * * Zyban * * is the first nicotine - free p = ill that, as part of a comprehensive program from your health care profes = sional, can help you stop smoking. Its prescription medicine available on = ly from your health care professional for smokers 18 and older. * * Click Here * * |! [] (3D " http: / / www. royalmeds. com / images / prop - head. jp =) - - - * * PROPECIA * * is a medical breakthrough =. The first pill that effectively treats manlike pattern hair loss on the ve = rtex (at top of head) and anterior mid - scalp area. * * Click Here * * * * * - - -! [] (3D " http: / / www. royalmeds. com / image =) = & = nbsp; * * Unsubscribe Inf = ormation: * * This email is intended to be a benefit to the recipient. If you would lik = e to opt - out and not receive any more marketing information please click = on the following link http: / / 194. 44. 46. 21 / remove. php. You = r address will be removed within 24hrs. We sincerely apologize for any in = convenience. vfyxeuedwacdjxriumtvrkybkfketsuq \\ - - DeathToSpamDeathToSpamDeathToSpam - - \\ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - This sf. net email is sponsored by: Jabber - The world \' s fastest growing real - time communications platform! Don \' t just IM. Build it in! http: / / www. jabber. com / osdn / xim _______________________________________________ Spamassassin - Sightings mailing list Spamassassin - Sightings @ lists. sourceforge. net hypertext transfer protocol: / / lists. sourceforge. net / lists / listinfo / spamassassin - sightings']
==================================================
'royal meds your online = pharmacy = b7 click here your online pharmacy for fda approv = ed drugs through a online consultation. no more awkward doctor visits, we offer confidential ordering onlin = e. take advantage of some of best prices uncommitted on the internet! we offer the widest range of drugs available through online ordering. = such as: |! (3d " URL royalmeds. com / images / viag head. jp =) = less than $ 7. 00 per dose viagra inten = ded for men with erectile dysfunction (ed ), it helps most men to get and = keep an erection when they get sexually excited. no need to go through em = barrassing, stressful situation anymore, you can now gravel viagra from the = comfort of your home. click here |! (3d " URL royalmeds. com / images / phen head. jp =) phentermine obesity weight loss dr = ug. it enables people to burn more fat doing nothing, stimulating your ne = rvous system. you will feel the difference! it will give you more energy, = you will become more active! it \' s an appetite suppressant, you \' ll burn f = at easier and eat less. it is a both safe and effective treatment to lose = weight. cli = ck here |! (3d " URL wide web. royalmeds. com / images / zyban head. j =) zyban is the first nicotine free p = ill that, as part of a comprehensive program from your health care profes = sional, can help you stop smoking. its prescription medicine available on = ly from your health care professional for smokers 18 and older. click here |! (3d " URL royalmeds. com / images / prop head. jp =) propecia is a medical breakthrough =. the first pill that effectively treats manlike pattern hair loss on the ve = rtex (at top of head) and anterior mid scalp area. click here ! (3d " URL royalmeds. com / image =) = & = nbsp; unsubscribe inf = ormation: this email is intended to be a benefit to the recipient. if you would lik = e to opt out and not receive any more marketing information please click = on the following link URL 44. 46. 21 / remove. php. you = r address will be removed within 24hrs. we sincerely apologize for any in = convenience. vfyxeuedwacdjxriumtvrkybkfketsuq \\ deathtospamdeathtospamdeathtospam \\ this sf. net email is sponsored by: jabber the world \' s fastest growing real time communications platform! don \' t just im. build it in! URL jabber. com / osdn / xim spamassassin sightings mailing list spamassassin sightings @ lists. sourceforge. net hypertext transfer protocol: / / lists. sourceforge. net / lists / listinfo / spamassassin sightings'

Hello list,
I think I've found another problem, or found a fix;
I have a ton of frozen mails in the mailq.
So, any ideas on how to clear?
I'm not exactly sure how to do that.
Thanks,
_______________________________________________
Speakup mailing list
Speakup@braille.uwo.ca
http://speech.braille.uwo.ca/mailman/listinfo/speakup


==================================================
hello list, i think i've found another problem, or found a fix; i have a ton of frozen mails in the mailq. so, any ideas on how to clear? i'm not exactly sure how to do that. thanks, speakup mailing list EMAIL URL

1.=09Limitation of Liability and Waiver of Consequential Damages. Notwiths= tanding anything herein to the contrary, the remedies provided under this C= onfirmation Letter and Master Agreement are the exclusive remedies availabl= e to the Parties. Under no circumstances shall the maximum aggregate liabi= lity of EPMI for damages under this Confirmation Letter and Master Agreemen= t exceed one hundred percent (100%) of the fees paid to EPMI under this Con= firmation Letter (the "Aggregate Limit"). The Aggregate Limit is the total= aggregate liability of EPMI under any theory of recovery, and includes but= is not limited to liquidated damages, warranty obligations, tort (includin= g negligence), breach of contract (including any breach resulting in termin= ation) and indemnity obligations. Neither party (nor their directors, offi= cers, employees, affiliates, or shareholders) shall be entitled to recover = incidental, indirect or consequential damages, including loss of profits, l= oss of business opportunities, loss of goodwill, increased operating costs,= or any other special or incidental damages, or any punitive or exemplary d= amages.
==================================================
1.=09limitation of liability and waiver of consequential damages. notwiths= tanding anything herein to the contrary, the remedies provided under this c= onfirmation letter and master agreement are the exclusive remedies availabl= e to the parties. under no circumstances shall the maximum aggregate liabi= lity of epmi for damages under this confirmation letter and master agreemen= t exceed one hundred percent (100%) of the fees paid to epmi under this con= firmation letter (the "aggregate limit"). the aggregate limit is the total= aggregate liability of epmi under any theory of recovery, and includes but= is not limited to liquidated damages, warranty obligations, tort (includin= g negligence), breach of contract (including any breach resulting in termin= ation) and indemnity obligations. neither party (nor their directors, offi= cers, employees, affiliates, or shareholders) shall be entitled to recover = incidental, indirect or consequential damages, including loss of profits, l= oss of business opportunities, loss of goodwill, increased operating costs,= or any other special or incidental damages, or any punitive or exemplary d= amages.

["and parents alike report says in the current environment where time it keister increase risks for children ' s scheduleswhat children classes in a begin as early as babyhood new online e shop lowest prices for yourself name our price honest to goodness price canyon eos escapenumberd digital slr camera escapenumber escapenumber escapenumber escapenumber escapenumber escapenumber apple escapenumber escapenumber macbook escapenumber escapenumber escapenumber escapenumber escapenumber apple ipod digital player hd escapenumber gb aac escapenumber escapenumber escapenumber escapenumber apple ipod video escapenumbergb black escapenumber escapenumber escapenumber escapenumber nikon descapenumber escapenumber escapenumber escapenumber escapenumber escapenumber escapenumber compaq presario escapenumber escapenumber escapenumber escapenumber escapenumber apple iphone escapenumbergb escapenumber escapenumber escapenumber escapenumber welcome go to web site mhln maillist mhln mailman eppg com http mailman eppg com mailman listinfo mhln"]
==================================================
"and parents alike report says in the current environment where time it keister increase risks for children ' s scheduleswhat children classes in a begin as early as babyhood new online e shop lowest prices for yourself name our price honest to goodness price canyon eos escapenumberd digital slr camera escapenumber escapenumber escapenumber escapenumber escapenumber escapenumber apple escapenumber escapenumber macbook escapenumber escapenumber escapenumber escapenumber escapenumber apple ipod digital player hd escapenumber gb aac escapenumber escapenumber escapenumber escapenumber apple ipod video escapenumbergb black escapenumber escapenumber escapenumber escapenumber nikon descapenumber escapenumber escapenumber escapenumber escapenumber escapenumber escapenumber compaq presario escapenumber escapenumber escapenumber escapenumber escapenumber apple iphone escapenumbergb escapenumber escapenumber escapenumber escapenumber welcome go to web site mhln maillist mhln mailman eppg com http mailman eppg com mailman listinfo mhln"

In [66]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(
    max_features=5000,
    ngram_range=(1,2),
    stop_words='english'
)

X = vectorizer.fit_transform(df['clean_text'])

In [67]:
from sklearn.model_selection import train_test_split

y = df['label']   # or your column name

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [70]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB(class_prior=[0.4, 0.6])
model.fit(X_train, y_train)

MultinomialNB(class_prior=[0.4, 0.6])

In [71]:
from sklearn.metrics import classification_report

y_pred = model.predict(X_test)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.98      0.92      0.95     41707
           1       0.84      0.96      0.90     17927

    accuracy                           0.93     59634
   macro avg       0.91      0.94      0.93     59634
weighted avg       0.94      0.93      0.94     59634

In [72]:
y_prob = model.predict_proba(X_test)[:, 1]

In [74]:
model.predict_proba(X_test[:3])

array([[6.11587423e-05, 9.99938841e-01],
       [5.03222386e-09, 9.99999995e-01],
       [7.48829152e-01, 2.51170848e-01]])